language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      script:
        - mkdir -p .cache
        - "tar --xattrs --xattrs-include=* -xf .cache/cache.tar || true"
        - docker run --privileged -v$PWD:/w -it fedora:26 /bin/sh -c "cd /w/install/linux && ./flatpak.sh"
      env: DEPLOY_FILE=install/linux/wxformbuilder.flatpak
      before_cache:
        - tar --xattrs --xattrs-include=* -cpf .cache/cache.tar install/linux/.flatpak-builder/
      cache:
        directories:
          - .cache
    - os: osx
      script:
        - brew update
        - brew upgrade boost
        - brew install wxmac boost dylibbundler
        - ./create_build_files4.sh --disable-mediactrl
        - make config=release -C build/3.0/gmake
        - cd output && zip -r wxFormBuilder_macOS.zip wxFormBuilder.app
      env: DEPLOY_FILE=output/wxFormBuilder_macOS.zip
