matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      script:
        - docker run --privileged -v$PWD:/w -it fedora:26 /bin/sh -c "cd /w/install/linux && ./flatpak.sh"
      env: DEPLOY_FILE=install/linux/wxformbuilder.flatpak
      cache:
        directories:
          - install/linux/.flatpak-builder
    - os: osx
      script:
        - brew update
        - brew install wxmac boost dylibbundler
        - ./create_build_files4.sh --disable-mediactrl
        - make config=release -C build/3.0/gmake
        - cd output && zip -r wxFormBuilder_macOS.zip wxFormBuilder.app
      env: DEPLOY_FILE=output/wxFormBuilder_macOS.zip
