sudo: required
services:
  - docker
script:
  - docker run --privileged -v$PWD:/w -it fedora:26 /bin/sh -c "cd /w/install/linux && ./flatpak.sh"
cache:
  directories:
    - install/linux/.flatpak-builder
