language: cpp
sudo: required
dist: trusty

matrix:
    include:
        - compiler: gcc
          env: GENERATOR="Unix Makefiles" CMAKE_PARAMS='-D CMAKE_C_COMPILER=gcc-4.9 -D CMAKE_CXX_COMPILER=g++-4.9'
        - os: osx
          compiler: clang
          osx_image: xcode8
          env: GENERATOR=Xcode

install: ./build/scripts/before_install.sh

script: ./build/scripts/travis-ci.sh
